# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-13 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carga_Horaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificação', models.CharField(max_length=30)),
                ('Atividade', models.TextField()),
                ('entrada_usuario', models.DateTimeField()),
                ('saida_usuario', models.DateTimeField()),
            ],
        ),
    ]
