# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-16 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atavirtual', '0002_auto_20160915_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargahoraria',
            name='entrada_usuario',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cargahoraria',
            name='saida_usuario',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
