# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 13:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('whatsapp', models.CharField(max_length=15)),
                ('cargo', models.CharField(choices=[('Aluno', 'Aluno'), ('Desenvolvimento Humano', 'Desenvolvimento Humano'), ('Administração', 'Administração')], default='Aluno', max_length=100)),
                ('efetivado', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('achando fácil', 'achando fácil'), ('tentando', 'tentando'), ('com dificuldades por problemas pessoais', 'com dificuldades por problemas pessoais'), ('em época de provas', 'em época de provas')], default='achando fácil', max_length=100)),
                ('user_referencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
