# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-16 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cargo',
            field=models.CharField(choices=[('Aluno', 'Aluno'), ('Trainee', 'Trainee'), ('Membro EJECT', 'Membro EJECT'), ('Desenvolvimento Humano', 'Desenvolvimento Humano'), ('Administração', 'Administração')], default='Aluno', max_length=100),
        ),
    ]
